# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160124_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='mood',
            field=models.IntegerField(null=True),
        ),
    ]
