# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='mood',
        ),
        migrations.AddField(
            model_name='document',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
