# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_document_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sandp500Close',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sandp500Open',
            field=models.DecimalField(decimal_places=10, max_digits=19, null=True),
        ),
    ]
